### ISSUE TITLE
创建的选项要如何设置使对方第一次进入客服系统时可以看到选项

### ISSUE THREAD

**Issue by vmox-7** [Haruka-Network/docs#1]
创建了选项，但是发现客户第一次进入客服系统时并不能之间看到选项并且点击进行自助解决问题。查阅了使用文档没有相关说明，需要进行额外的设置吗
![屏幕截图 2024-11-11 194427](https://github.com/user-attachments/assets/0d901fc2-aba0-477c-8182-6645131f4337)

**Comment by vmox-7** [comment]
自动回复板块的选项类型选择回复选项也无法使用，既不能选择选项也不能手动输入文本。改功能尚未完善还是需要进行额外设置还是需要特定的设备才可以使用
![屏幕截图 2024-11-11 201317](https://github.com/user-attachments/assets/f78435d1-eb8b-4b4f-b320-4afd685a206c)

**Comment by DyAxy** [comment]
目前暂未支持，后续会增加支持

**Comment by vmox-7** [comment]
好的感谢

**Comment by vmox-7** [comment]
> 目前暂未支持，后续会增加支持
发现是我自己不会设置，原来现在是和自动回复搭配使用的，非常抱歉

**Comment by vmox-7** [comment]
发现创建的选项似乎不支持删除嘞

**Comment by DyAxy** [comment]
未来版本会增加删除选项
