### ISSUE TITLE
人工介入切换时间无法修改（付费用户）

### ISSUE THREAD

**Issue by w243420707** [Haruka-Network/docs#2]
![image](https://github.com/user-attachments/assets/a6b84cd5-d8ac-4907-8dfd-b574593c7d03)

无论修改为多少点击保存的时候都会变成1800

- [x] 是付费用户

另外站点里没有你们的联系方式呀

**Comment by DyAxy** [comment]
我们尽快处理，可以通过tg群：https://t.me/dyaogroup

在 2024年12月3日星期二，www ***@***.***> 写道：
